import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'idea'
    id 'maven-publish'
    id 'multiloader-loader'
    id 'com.modrinth.minotaur'
    id 'net.fabricmc.fabric-loom'
    id 'net.darkhax.curseforgegradle'
}

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}-${release_cycle}";
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

loom {

    // If the access widener exists, include it.
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            setConfigName("Fabric Dist: Client")
            // preferGradleTask(true)
            ideConfigGenerated(true)
            runDir("run")
            vmArg "-Dmixin.debug.export=true"
        }
        server {
            server()
            setConfigName("Fabric Dist: Server")
            // preferGradleTask(true)
            ideConfigGenerated(true)
            runDir("run")
            vmArg "-Dmixin.debug.export=true"
        }
        data {
            inherit client
            setConfigName("Fabric Dist: Data")
            // preferGradleTask(true)
            ideConfigGenerated(true)
            runDir("build/datagen")

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":platform_agnostic").file("src/main/generated")}"
        }
    }
}

// sourceSets.main.java.srcDir '../sources-clothconfig'

sourceSets.main.resources.srcDir 'src/generated/resources'

task curseforge(type: TaskPublishCurseForge) {
    dependsOn(jar)
    description = 'Publishes the Fabric build to CurseForge.'
    group = 'publishing'

    apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

    def mainFile = upload(curseforge_project_id, project.layout.buildDirectory.file("libs/${base.archivesName.get()}-${version}.jar").get().getAsFile())
    mainFile.changelog = rootProject.file('CHANGELOG.md').text
    mainFile.addRequirement("fabric-api");
    project.minecraft_versions.split(',').toList().each { mainFile.addGameVersion(it) }
    mainFile.releaseType = rootProject.ConstructCurseForgeReleaseTypeString(release_cycle)
    mainFile.addModLoader("Fabric");
    mainFile.addEnvironment("Client", "Server");
}

modrinth {
    token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
    projectId = project.modrinth_project_id
    versionType = rootProject.ConstructModrinthReleaseTypeString(release_cycle)
    versionNumber = project.version + "+fabric-" + project.minecraft_version
    uploadFile = jar
    changelog = rootProject.file("CHANGELOG.md").text
    gameVersions = project.minecraft_versions.split(',').toList()
    syncBodyFrom = rootProject.file("modpage.md").text
    loaders = ['fabric']
    dependencies {
        required.project "fabric-api"
    }
}

publishing {
    publications {
        gpr(MavenPublication) {
            defaultTasks("remapJar", "sourcesJar")
        }
    }
}

tasks.modrinth.dependsOn(jar)