plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
    version = project.version
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

repositories {
    mavenCentral()
    // https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups("org.spongepowered") }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:24.1.0'
}

['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${mod_name}" }
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version,
                'MixinConfigs'          : "${mod_id}.mixins.json,${mod_id}.${project.name}.mixins.json",
        ])
    }
}

processResources {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${mod_name}" }
    }

    var expandProps = [
            'version'                      : version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'neoforge_version'             : neoforge_version,
            'neoforge_version_range'       : neoforge_version_range,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            'mod_menu_version'             : mod_menu_version,
            'cloth_config_api_version'     : cloth_config_api_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'homepage'                     : homepage,
            'sources'                      : sources,
            'issues'                       : issues,
            "forge_version"                : forge_version,
            "forge_version_range"          : forge_version_range,
            "forge_loader_version_range"   : forge_loader_version_range,
            "credits"                      : credits,
            "java_version"                 : java_version,

    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    repositories {
        maven {
            name = "mdcdi1315_BML_Repo"
            url = uri("https://maven.pkg.github.com/mdcdi1315/mdcdi1315_base_mods_lib")
            credentials {
                username = project.findProperty("github.user") ?: System.getenv("GITHUB_PKG_USERNAME")
                password = project.findProperty("github.key") ?: System.getenv("GITHUB_PKG_API_TOKEN")
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            defaultTasks("jar", "sources")
            pom {
                groupId = project.group
                artifactId = "bml-${project.name}-${minecraft_version}"
                version = project.version

                name = "mdcdi1315's BML"
                description = "mdcdi1315's Base Mods Library - ${project.name} project - Version ${project.version}"
                scm {
                    url = "https://github.com/mdcdi1315/mdcdi1315_base_mods_lib"
                }
                developers {
                    developer {
                        id = 'mdcdi1315'
                        name = 'mdcdi1315'
                    }
                }
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://github.com/mdcdi1315/mdcdi1315_base_mods_lib/tree/1.21.1/LICENSE"
                    }
                }
            }

            from components.java
        }
    }
}