plugins {
    id 'fabric-loom' version '1.10.1' apply(false)
    id 'com.modrinth.minotaur' version '2.+' apply(false)
    id 'net.neoforged.moddev' version '2.0.107' apply(false)
    id 'net.darkhax.curseforgegradle' version '1.1.26' apply(false)
}

subprojects {
	configurations.configureEach {
		resolutionStrategy {
			cacheChangingModulesFor 60, 'seconds'
			cacheDynamicVersionsFor 60, 'seconds'
		}
	}
}

tasks.register("full_publish") {
    group = 'publishing'
    description = "Publishes all the Jar archives to GitHub for developers, and CurseForge for consumers."

    it.dependsOn(":fabric:publish", ":forge:publish", ":neoforge:publish", ":fabric:curseforge", ":forge:curseforge", ":neoforge:curseforge", ":platform_agnostic:publish")
}