plugins {
    id 'com.modrinth.minotaur' version '2.+' apply(false)
    id 'net.neoforged.moddev' version '2.0.147' apply(false)
    id 'net.darkhax.curseforgegradle' version '1.1.26' apply(false)
    id 'net.fabricmc.fabric-loom' version '1.18-SNAPSHOT' apply(false)
}

subprojects {
	configurations.configureEach {
		resolutionStrategy {
			cacheChangingModulesFor 60, 'seconds'
			cacheDynamicVersionsFor 60, 'seconds'
		}
	}
}

public static String ConstructCurseForgeReleaseTypeString(String release_cycle)
{
    if (release_cycle.equalsIgnoreCase("DEV")) {
        return "alpha";
    } else if (release_cycle.equalsIgnoreCase("RC") || release_cycle.equalsIgnoreCase("PR")) {
        return "beta";
    } else if (release_cycle.equalsIgnoreCase("Stable")) {
        return "release";
    } else {
        throw new IllegalArgumentException("The given release cycle is invalid: " + release_cycle);
    }
}

// Currently, the constants used by modring
public static String ConstructModrinthReleaseTypeString(String release_cycle)
{
    if (release_cycle.equalsIgnoreCase("DEV")) {
        return "alpha";
    } else if (release_cycle.equalsIgnoreCase("RC") || release_cycle.equalsIgnoreCase("PR")) {
        return "beta";
    } else if (release_cycle.equalsIgnoreCase("Stable")) {
        return "release";
    } else {
        throw new IllegalArgumentException("The given release cycle is invalid: " + release_cycle);
    }
}

tasks.register("full_publish") {
    group = 'publishing'
    description = "Publishes all the Jar archives to GitHub for developers, and CurseForge for consumers."

    it.dependsOn(
            ":fabric:publish",
            ":neoforge:publish",
            ":fabric:curseforge",
            ":neoforge:curseforge",
            ":platform_agnostic:publish"
    )
}

tasks.register("publish_to_packages_only") {
    group = 'publishing'
    description = "Publishes all the Jar archives to GitHub for developers. Use full_publish for also publishing to CurseForge."

    it.dependsOn(":fabric:publish", ":neoforge:publish", ":platform_agnostic:publish")
}

tasks.register("ap_publish") {
    group = 'publishing'
    description = "Publishes the Annotation Processor project to GitHub for developers."

    it.dependsOn(":annotation_processor:publish");
}