# Mod Properties
# Recommended Versioning Scheme: https://docs.neoforged.net/docs/gettingstarted/versioning/
version = 1.0.26
# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = mdcdi1315_base_mods_lib
mod_name = mdcdi1315's Base Mods Library
# Your group should be a unique identifier in reverse domain format.
group = com.github.mdcdi1315
description=Provides essential hooks and the base API's for mdcdi1315's mods.
# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage=https://www.curseforge.com/minecraft/mc-mods/mdcdi1315-base-lib
sources=https://github.com/mdcdi1315/mdcdi1315_base_mods_lib
issues=https://github.com/mdcdi1315/mdcdi1315_base_mods_lib/issues
discord=
# Make sure the license here matches the one you defined in the LICENSE file.
license=MIT License
mod_author = mdcdi1315
# Specify here whether this mod version is stable, a pre-release, a snapshot or a release-candidate.
# Stable Versions: Stable
# Pre-release Versions: PR
# Release Candidates: RC
# Development versions: DEV
release_cycle = Stable
# Credits can include other attribution as well, such as artists, etc.
credits=

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_release_type = release
curseforge_project_id = 1379583
modrinth_release_type = release
modrinth_project_id = 0

# Minecraft Properties
# The Minecraft version your mod is built against. This is the version of Minecraft that will be loaded into your development environment.
minecraft_version = 1.21.5
# A list of Minecraft versions that your mod supports. This is used as metadata for CurseForge and Modrinth.
minecraft_versions = 1.21.5
# The version range that your mod can run on. It's hard to predict what minor version will introduce breaking changes, so I recommend just setting the next major version as upper limit.
minecraft_version_range = [1.21.5,1.21.6)
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 21

# Common Properties
# Parchment adds human-readable names to parameters. You can find the latest version at: https://parchmentmc.org/docs/getting-started
parchment_minecraft = 1.21.5
parchment_version = 2025.06.15
# NeoForm version for use in the platform-agnostic project. Versions can be found at https://projects.neoforged.net/neoforged/neoform.
neo_form_version = 1.21.5-20250325.162830

# Forge Properties
# The Forge version to use. You can find all versions on their website: https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version = 55.1.0
# The minimum Forge versions to use. You should set this if you are using a Forge feature that is not available in older versions.
forge_version_range = [55,)
forge_loader_version_range = [55,)
forge_mixins=true

# NeoForge Properties
# The NeoForge version to use. You can find all versions on their website: https://neoforged.net/
neoforge_version = 21.5.90
# The NeoForge version range to use.
neoforge_version_range = [21.5.90,)
# The NeoForge loader version range to use.
neoforge_loader_version_range = [1,)

# Fabric Properties
# The Fabric versions to use. You can find the latest version on their website: https://fabricmc.net/develop/
# This is the Fabric API version.
fabric_version = 0.128.2+1.21.5
# This is the Fabric Loader version.
fabric_loader_version = 0.17.3

# Dependencies
# You can add additional properties here and reference them in your `dependencies.gradle` files.
mixin_version=0.8.5
# Mod Menu version. Used in fabric.mod.json and in dependency inclusion. See versions in https://www.curseforge.com/minecraft/mc-mods/modmenu.
mod_menu_version=14.0.0-rc.2
# Cloth Config API version. Used in fabric.mod.json and in dependency inclusion. See versions in https://www.curseforge.com/minecraft/mc-mods/cloth-config.
cloth_config_api_version=18.0.145

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false