blank_issues_enabled: false
contact_links:
  name: mdcdi1315's Base Mods Library discussions
  url: https://github.com/mdcdi1315/mdcdi1315_base_mods_lib/discussions
  about: Please ask and answer questions and/or for new library features here instead.
