plugins {
    id 'java-library'
}

def lib_version = "1.0.2"

base {
    version = lib_version
    archivesName = "bml_language_loader"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

jar {
    manifest.attributes([
            'FMLModType'            : "LIBRARY",
            'Specification-Title'   : "BML_LANGUAGE_PROVIDER",
            'Specification-Vendor'  : "mdcdi1315",
            'Specification-Version' : lib_version,
            'Implementation-Title'  : "BML_LANGUAGE_PROVIDER_NEOFORGE_FML",
            'Implementation-Vendor' : "mdcdi1315",
            'Implementation-Version': lib_version
    ])
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'