plugins {
    id 'java-library'
    id 'maven-publish'
}

def lib_version = "1.0.1"

base {
    version = lib_version
    archivesName = "bml_annotation_processor"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

jar {
    manifest.attributes([
            'Specification-Title'   : "BML_ANNOTATION_PROCESSOR",
            'Specification-Vendor'  : "mdcdi1315",
            'Specification-Version' : lib_version,
            'Implementation-Title'  : "BML_ANNOTATION_PROCESSOR",
            'Implementation-Vendor' : "mdcdi1315",
            'Implementation-Version': lib_version
    ])
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

publishing {
    repositories {
        maven {
            name = "mdcdi1315_BML_Repo"
            url = uri("https://maven.pkg.github.com/mdcdi1315/mdcdi1315_base_mods_lib")
            credentials {
                username = project.findProperty("github.user") ?: System.getenv("GITHUB_PKG_USERNAME")
                password = project.findProperty("github.key") ?: System.getenv("GITHUB_PKG_API_TOKEN")
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            defaultTasks("jar")
            pom {
                groupId = project.group
                version = project.version
                artifactId = "bml_${project.name}"

                name = "mdcdi1315's BML Annotation Processor"
                description = "mdcdi1315's Base Mods Library - AP project - Version ${project.version}"
                scm {
                    url = "https://github.com/mdcdi1315/mdcdi1315_base_mods_lib"
                }
                developers {
                    developer {
                        id = 'mdcdi1315'
                        name = 'mdcdi1315'
                    }
                }
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://github.com/mdcdi1315/mdcdi1315_base_mods_lib/tree/1.21.1/LICENSE"
                    }
                }
            }

            from components.java
        }
    }
}